apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_HOST: {{ .Values.config.host | quote }}
  APP_PORT: {{ .Values.service.port | quote }}
  APP_MONGODBURI: {{ .Values.config.mongodbUri | quote }}
  APP_MONGODBNAME: {{ .Values.config.mongodbName | quote }}
  APP_AUTHUSERNAME: {{ .Values.config.authUsername | quote }}
  APP_AUTHPASSWORD: {{ .Values.config.authPassword | quote }}
